// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpJp5fM6VD28Y0AKQjPykDI0K5lqPL40',
    appId: '1:935300248020:web:10e5d008037ad73cc8e641',
    messagingSenderId: '935300248020',
    projectId: 'chat-app-fd778',
    authDomain: 'chat-app-fd778.firebaseapp.com',
    storageBucket: 'chat-app-fd778.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCDei322yraDYIhOpkeYHj-Px1SStnEQ',
    appId: '1:935300248020:android:baf9e7ae5139a81fc8e641',
    messagingSenderId: '935300248020',
    projectId: 'chat-app-fd778',
    storageBucket: 'chat-app-fd778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLLFt8A8w6D1_srFnNMM56DWS0sObTTQ',
    appId: '1:935300248020:ios:0b9571a470dbb78dc8e641',
    messagingSenderId: '935300248020',
    projectId: 'chat-app-fd778',
    storageBucket: 'chat-app-fd778.firebasestorage.app',
    androidClientId: '935300248020-r23kk4qgpdav82cbrappkm88nr3ul4v7.apps.googleusercontent.com',
    iosClientId: '935300248020-32v9os2ahila9r3sr3dneqbobk43u1s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}